### ISSUE TITLE
help

### ISSUE THREAD

**Issue by UnemployedAutist** [momentumdevelopment/dumper#1]
When i try dump (with argument package name) console write it:
java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @54bedef2                                            at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)                        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)                        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)                                            at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)                                                    at me.zeroeightsix.kami.Main.main(Main.java:38)                                                                 java.lang.NoSuchFieldException: sys_paths                                                                                       at java.base/java.lang.Class.getDeclaredField(Class.java:2610)                                                          at me.zeroeightsix.kami.Main.attach(Main.java:56)                                                                       at me.zeroeightsix.kami.Main.main(Main.java:44)    
i have JAVA_HOME (jdk1.8.0_331)

**Comment by PotatoSUS** [comment]
run the cmd with admin 🧠

**Comment by UnemployedAutist** [comment]
did not help
